### ISSUE TITLE
Could you add a feature to automatically pop up the loot frame after a boss is defeated, or whenever someone in a party, raid, or LFR loots an item?

### ISSUE THREAD

**Issue by moshouchajian** [Rebbekha/BegForLoot#5]
Could you add a feature to automatically pop up the loot frame after a boss is defeated, or whenever someone in a party, raid, or LFR loots an item?

**Comment by Rebbekha** [comment]
Normally if the other player can give you the object it will automatically pop up the loot frame. If it's for anniversary LFR becareful you can't trade the warband item.

If it's not that tell me in which instance it doesn't open
