### ISSUE TITLE
When I loot items in Timewalking dungeons, LFR, Mythic+, or Aberrus, an error occurs.

### ISSUE THREAD

**Issue by moshouchajian** [Rebbekha/BegForLoot#6]
Interface/AddOns/BegForLoot/src/LootEvent.lua:514: attempt to call global 'GetItemStats' (a nil value)
Count: 2

Call Stack:
[string "=[C]"]: in function `GetItemStats'
[string "@Interface/AddOns/BegForLoot/src/LootEvent.lua"]:514: in function <Interface/AddOns/BegForLoot/src/LootEvent.lua:513>
[string "@Interface/AddOns/BegForLoot/src/LootEvent.lua"]:646: in function <Interface/AddOns/BegForLoot/src/LootEvent.lua:614>
[string "@Interface/AddOns/BegForLoot/src/LootEvent.lua"]:1023: in function `callback'
[string "@Interface/AddOns/BegForLoot/src/LootEvent.lua"]:561: in function <Interface/AddOns/BegForLoot/src/LootEvent.lua:525>
[string "@Interface/AddOns/BegForLoot/src/LootEvent.lua"]:1016: in function `func'
[string "@Interface/AddOns/BegForLoot/src/events/event-manager.lua"]:46: in function `Fire'
[string "@Interface/AddOns/BegForLoot/src/events/event-manager.lua"]:61: in function <...rface/AddOns/BegForLoot/src/events/event-manager.lua:60>

**Comment by Rebbekha** [comment]
I'm working on it

**Comment by Rebbekha** [comment]
I found the problem and resolve it. The method GetItemStats is deprecated in retail and work in classic. I will push a release soon and it will be ok
